from CONFIG.RUNTIME_PARAMETERS import *


def target_db_config():
    config = {"MAX_TARGET_CHAIN_LENGTH": MAX_TARGET_CHAIN_LENGTH}
    return config


# runtime_config is saved inside WORK_PATH / project_name / project_config.json
# and will be used for all upcoming tasks in this project
def runtime_config():
    config = {
        "DEEPFRI_PROCESSING_MODES": DEEPFRI_PROCESSING_MODES,
        "MAX_QUERY_CHAIN_LENGTH": MAX_QUERY_CHAIN_LENGTH,
        "ANGSTROM_CONTACT_THRESHOLD": ANGSTROM_CONTACT_THRESHOLD,
        "GENERATE_CONTACTS": GENERATE_CONTACTS,
        "MMSEQS_MIN_BIT_SCORE": MMSEQS_MIN_BIT_SCORE,
        "MMSEQS_MAX_EVAL": MMSEQS_MAX_EVAL,
        "MMSEQS_MIN_IDENTITY": MMSEQS_MIN_IDENTITY,
        "PAIRWISE_ALIGNMENT_MATCH": PAIRWISE_ALIGNMENT_MATCH,
        "PAIRWISE_ALIGNMENT_MISSMATCH": PAIRWISE_ALIGNMENT_MISSMATCH,
        "PAIRWISE_ALIGNMENT_GAP_OPEN": PAIRWISE_ALIGNMENT_GAP_OPEN,
        "PAIRWISE_ALIGNMENT_GAP_CONTINUATION": PAIRWISE_ALIGNMENT_GAP_CONTINUATION,
        "ALIGNMENT_MIN_SEQUENCE_IDENTITY": ALIGNMENT_MIN_SEQUENCE_IDENTITY,
    }
    return config
