import multiprocessing
CPU_COUNT = multiprocessing.cpu_count()

MAX_CHAIN_LENGTH = 2500
ANGSTROM_CONTACT_THRESHOLD = 6
GENERATED_CONTACTS = 2

PAIRWISE_ALIGNMENT_GAP_OPEN = 0
PAIRWISE_ALIGNMENT_GAP_CLOSE = 0
PAIRWISE_ALIGNMENT_MMSEQS_MIN_BIT_SCORE = 0
PAIRWISE_ALIGNMENT_MMSEQS_MAX_EVAL = 0
PAIRWISE_ALIGNMENT_MMSEQS_MAX_COMPARISONS = 0
